pages:
  image: node:24
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - make generate
    - rm -rvf .output/public/github .output/public/linkedin
    - echo "{\"status\":\"up\", \"commit\":\"$CI_COMMIT_SHORT_SHA\", \"built_at\":\"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"}" > .output/public/health.json
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  artifacts:
    paths:
      - .output/public
  publish: .output/public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
