services:
  app:
    image: ghcr.io/afonsodemori/devcontainers/node:24-20260416-064128
    command: sleep infinity
    networks:
      shared:
        aliases:
          - afonsodev.localhost

networks:
  shared:
    external: true
    name: devcontainer-network
